Repository comprehensive-design/style_scanner_frontend, pull requests merged in 2024-09, with the labels that each got.

#122 [Refact] 회원가입 페이지 재구성
  src/pages/register/Register.js
  src/pages/register/Register.module.css
  src/pages/register/RegisterForm.js
  src/style/style.css
Labels: UI, Feat

#129 Refact/#112 item hook
  src/App.js
  src/Components/feed/Feed.js
  src/hooks/useFeedClickLogic.js
  src/pages/home/HomeFeed.js
  src/pages/homeItem/HomeItem.js
  src/utils/axios.jsx
Labels: wontfix

#148 Refact/#121 community write post
  src/hooks/useHomeItemLogic.js
  src/hooks/useMe.js
  src/hooks/useWritePost.js
  src/pages/community/popup/WritePopup.js
  src/pages/home/HomeFeed.js
  src/pages/homeItem/HomeItem.js
Labels: Performance

#150 Refact/#121 community
  src/hooks/useComment.jsx
  src/hooks/useCommunity.js
  src/pages/community/detail/CommunityDetail.js
  src/pages/community/detail/comment/Comment.js
  src/pages/community/home/Community.js
  src/pages/community/home/feed/comfeed.js
  src/pages/community/popup/WritePopup.js
  src/style/style.css
  src/utils/ConvertProxyImage.js
Labels: Performance
