Repository comprehensive-design/style_scanner_frontend, pull requests merged in 2024-05, with the labels that each got.

#36 커스텀 버튼 생성
  src/Components/Button.js
Labels: good first issue

#57 [UI] 커뮤니티 알림 - 페이지네이션, 푸터 추가 #56
  src/Components/CommunityNoti.js
  src/css/CommunityNoti.module.css
Labels: UI, Feat

#60 홈-아이템 수정
  src/Components/HomeInfo.js
  src/Components/ItemInfo.js
  src/Components/MyPageComments.js
  src/css/HomeInfo.module.css
  src/css/ItemInfo.module.css
Labels: enhancement

#77 [BugFix] 로그인 css 오류 해결
  src/Components/Login.js
  src/Components/LoginForm.js
  yarn.lock
Labels: Bug Fix

#81 [Feat] Axios get
  src/Components/HomeFeed.js
  src/Components/HomeInfo.js
  src/Components/ItemInfo.js
  src/Components/feed.js
Labels: Feat

#78 [Feat] 회원가입 백엔드 서버 연결 #73
  package-lock.json
  src/Components/Register.js
  src/Components/RegisterForm.js
  src/css/Register.module.css
  yarn.lock
Labels: UI, Feat, Bug Fix

#84 UserList, FollowingList 기능추가 #75, #83
  .env
  src/App.js
  src/Components/CommentBox.js
  src/Components/FeedPopup.js
  src/Components/FollowingList.js
  src/Components/ItemInfo.js
  src/Components/Login.js
  src/Components/Register.js
  src/Components/UserFeed.js
  src/Components/UsersList.js
  src/Components/channel.js
  src/css/FeedPopup.module.css
  src/css/UsersList.module.css
Labels: enhancement, Feat

#79 [Feat] 로그인 백엔드 서버 연결 #76
  src/Components/Login.js
Labels: Feat

#91 Mainbar의 Search 기능 추가 #90
  src/App.js
  src/Components/MainBar.js
  src/Components/Search.js
  src/Components/SearchBar.js
  src/css/Search.module.css
Labels: enhancement, Improvement, Feat, Bug Fix

#92 [Feat, UI] 메인화면 UI 및 기능 구현 #89
  public/img/Main1.png
  public/img/Main2.png
  public/img/Main3.png
  public/img/Main4.png
  public/img/Main5.png
  src/Components/Dot.js
  src/Components/Main.js
  src/Components/MainBar.js
  src/css/Main.module.css
  src/css/MainBar.module.css
Labels: UI, Feat

#88 Account manage server connect #87
  public/img/profile.png
  public/img/whiteBox.png
  src/Components/AccountManage.js
  src/Components/AccountManageForm.js
  src/Components/ManageBox.js
  src/Components/MypageDefault.js
  src/Components/MypageDefaultForm.js
  src/Components/Popup.js
  src/css/AccountManage.module.css
Labels: UI, Performance, Feat

#96 [Bug, UI] 마이페이지 기본 css 수정
  src/Components/AccountManageForm.js
  src/Components/MypageDefault.js
  src/Components/MypageDefaultForm.js
  src/css/MypageDefault.module.css
Labels: UI, Bug Fix

#104 [API] Community, Comment API연결
  public/img/image.png
  public/img/image1.png
  src/Components/CommentInfo.js
  src/Components/CommunityFeed.js
  src/Components/CommunityInfo.js
  src/Components/ItemInfo.js
  src/Components/comfeed.js
  src/css/CommentInfo.module.css
  src/css/CommunityInfo.module.css
Labels: enhancement, Feat, Bug Fix
